name: "🚨 Availability Event"
description: Report an availability event
title: "[Issue Notice] YYYY-MM-DD - {brief description of event}"
labels: ["service availability"]
assignees: []
body:
  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Ongoing
        - In recovery
        - Resolved
    validations:
      required: true
  - type: input
    id: start_time
    attributes:
      label: Start Time
      placeholder: YYYY/MM/DD hh:mm UTC
      description: Start Date and Time (UTC)
    validations:
      required: true      
  - type: textarea
    id: description
    attributes:
      label: Event Summary
      value: |        
        A clear and concise summary of the event.
    validations:
      required: true
  - type: textarea  
    id: timeline
    attributes:
      label: Event Timeline
      value: |
        1. 10/20/2025 12:00 AM UTC ...
        2. ...
  - type: textarea  
    id: alarms
    attributes:
      label: Relevant Alarm Thresholds Breached
      value: |
        Description of alarms and thresholds which were breached

  - type: textarea
    id: footer
    attributes:
      label: '---'
      value: |
        For latest status, see https://health.aws.amazon.com/health/status
